# A dictionary for normalizing raw extracted terms into standardized identities.
# Key: Raw term (lowercase)
# Value: Normalized canonical term

SKILL_ONTOLOGY = {
    # Programming Languages
    "python 3": "Python",
    "python programming": "Python",
    "python": "Python",
    "java": "Java",
    "c++": "C++",
    "cpp": "C++",
    "c#": "C#",
    "c sharp": "C#",
    "javascript": "JavaScript",
    "js": "JavaScript",
    "typescript": "TypeScript",
    "ts": "TypeScript",
    "golang": "Go",
    "go": "Go",
    "rust": "Rust",
    "ruby": "Ruby",
    "php": "PHP",
    "swift": "Swift",
    "kotlin": "Kotlin",
    "r": "R",
    "r programming": "R",
    "html": "HTML",
    "html5": "HTML",
    "css": "CSS",
    "css3": "CSS",
    "bash": "Bash",
    "shell": "Shell",
    
    # ML/AI & Data Science
    "machine learning": "Machine Learning",
    "ml": "Machine Learning",
    "deep learning": "Deep Learning",
    "dl": "Deep Learning",
    "natural language processing": "NLP",
    "nlp": "NLP",
    "computer vision": "Computer Vision",
    "cv": "Computer Vision",
    "reinforcement learning": "Reinforcement Learning",
    "rl": "Reinforcement Learning",
    "large language models": "LLMs",
    "llms": "LLMs",
    "llm": "LLMs",
    "generative ai": "Generative AI",
    "genai": "Generative AI",
    
    # Frameworks & Libraries
    "pytorch framework": "PyTorch",
    "pytorch": "PyTorch",
    "torch": "PyTorch",
    "tensorflow": "TensorFlow",
    "tf": "TensorFlow",
    "keras": "Keras",
    "scikit-learn": "Scikit-Learn",
    "sklearn": "Scikit-Learn",
    "pandas": "Pandas",
    "numpy": "NumPy",
    "matplotlib": "Matplotlib",
    "seaborn": "Seaborn",
    "opencv": "OpenCV",
    "transformers": "Transformers",
    "huggingface": "Hugging Face",
    "hugging face": "Hugging Face",
    "spacy": "spaCy",
    "nltk": "NLTK",
    "xgboost": "XGBoost",
    "lightgbm": "LightGBM",
    "langchain": "LangChain",
    
    # Databases & SQL
    "sql": "SQL",
    "mysql": "MySQL",
    "postgresql": "PostgreSQL",
    "postgres": "PostgreSQL",
    "mongodb": "MongoDB",
    "mongo": "MongoDB",
    "redis": "Redis",
    "cassandra": "Cassandra",
    "elasticsearch": "Elasticsearch",
    "sqlite": "SQLite",
    "oracle": "Oracle",
    "nosql": "NoSQL",
    
    # Cloud & DevOps
    "aws": "AWS",
    "amazon web services": "AWS",
    "gcp": "GCP",
    "google cloud": "GCP",
    "azure": "Azure",
    "microsoft azure": "Azure",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "k8s": "Kubernetes",
    "terraform": "Terraform",
    "ansible": "Ansible",
    "jenkins": "Jenkins",
    "ci/cd": "CI/CD",
    "cicd": "CI/CD",
    "linux": "Linux",
    "unix": "Unix",
    "ubuntu": "Ubuntu",
    "git": "Git",
    "github": "GitHub",
    "gitlab": "GitLab",
    "bitbucket": "Bitbucket",
    "mlops": "MLOps",
    
    # Web & App Development
    "react": "React",
    "reactjs": "React",
    "react.js": "React",
    "react native": "React Native",
    "angular": "Angular",
    "angularjs": "Angular",
    "vue": "Vue.js",
    "vuejs": "Vue.js",
    "vue.js": "Vue.js",
    "next.js": "Next.js",
    "nextjs": "Next.js",
    "node.js": "Node.js",
    "nodejs": "Node.js",
    "node": "Node.js",
    "express": "Express.js",
    "expressjs": "Express.js",
    "express.js": "Express.js",
    "django": "Django",
    "flask": "Flask",
    "fastapi": "FastAPI",
    "spring boot": "Spring Boot",
    "graphql": "GraphQL",
    "rest api": "REST APIs",
    "rest": "REST APIs",
    
    # Data Engineering
    "apache spark": "Apache Spark",
    "spark": "Apache Spark",
    "hadoop": "Hadoop",
    "kafka": "Apache Kafka",
    "apache kafka": "Apache Kafka",
    "airflow": "Apache Airflow",
    "snowflake": "Snowflake",
    "databricks": "Databricks",
    "dbt": "dbt",
    
    # Methodologies & Concepts
    "agile": "Agile",
    "scrum": "Scrum",
    "jira": "Jira",
    "tdd": "TDD",
    "test driven development": "TDD",
    "object oriented programming": "OOP",
    "oop": "OOP",
    "data structures": "Data Structures",
    "algorithms": "Algorithms"
}

# Critical hard skills that must always be checked via regex fallback
CRITICAL_SKILLS = set(SKILL_ONTOLOGY.values())

def normalize_skill(skill_text):
    """Normalize a skill using the ontology."""
    normalized = skill_text.strip().lower()
    return SKILL_ONTOLOGY.get(normalized, skill_text.strip())
